# fly.toml app configuration file generated for express-app on 2023-06-06T10:15:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "express-app"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
  image = "sreimavuo/express-app:latest"

